# Generated by Django 6.0.2 on 2026-03-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('dese', models.CharField(max_length=300)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
