# Generated by Django 6.0.2 on 2026-03-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_pieces_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pieces',
        ),
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='shop/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcatagory',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
